org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.18.2
loader_version=0.18.1
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_id=astralgenerators
mod_name=Astral Generators
mod_version=2.0.0-alpha
mod_description=An addon for Create: Astral
mod_license=MIT
maven_group=dev.tobynguyen27

# Dependencies
fabric_version=0.77.0+1.18.2
fabric_kotlin_version=1.13.8+kotlin.2.3.0
porting_lib_version=1.2.1304-beta+1.18.2
forge_tags_version=2.1
registrate_version=MC1.18.2-1.1.11
codebebelib=2.0.0-build.2
libgui_version=5.4.2+1.18.2
energy_api_version=2.3.0
jade_version=5.100.0
jade_addons_version=2.2.0
lazydfu_version=0.1.2
rei_version=8.4.737

modmenu_version=3.2.5
